caselawg/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views 

urlpatterns = [
    path('accounts/signup/', views.signup, name='signup'),
    path('', views.Home.as_view(), name='home'),
    path("about/", views.about, name="about"),
    path('cases/', views.case_index, name='case-index'),
    path('cases/<int:pk>/', views.case_detail, name='case-detail'),
    path('case/create/', views.CaseCreate.as_view(), name='case-create'),
    path('case/<int:pk>/update/', views.CaseUpdate.as_view(), name='case-update'),
    path('case/<int:pk>/close/', views.CaseCloseView.as_view(), name='case-close'),
    path('case/<int:pk>/delete/', views.CaseDelete.as_view(), name='case-delete'),
    path('case/<int:pk>/task/create/', views.TaskCreate.as_view(), name='task-create'),
    path('tasks/', views.task_index, name='task-index'),
    path('tasks2/', views.task_index2, name='task-index2'), #test url
    path('tasks/<int:pk>/', views.task_detail, name='task-detail'),
    path('task/<int:pk>/update/', views.TaskUpdate.as_view(), name='task-update'),
    path('task/<int:pk>/close/', views.TaskCloseView.as_view(), name='task-close'),
    path('task/<int:pk>/delete/', views.TaskDelete.as_view(), name='task-delete'),
    path('tasksapi/', views.tasksDataAPI, name='tasks-api'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
import datetime

CASESTATUS = (
    ('A', 'Open-Active'),
    ('I', 'Open-Inactive'),
    ('C', 'Closed')
)

CASESTAGE = (
    ('1', 'Intake'),
    ('2', 'Complaint'),
    ('3', 'Pre-Trial Motions/Discovery'),
    ('4', 'Trial Preparation'),
    ('5', 'Trial'),
    ('6', 'Mediation'),
    ('7', 'Arbitration'),
    ('8', 'Settlement'),
    ('9', 'MISC')
)

TASKTYPE = (
    ('1', 'Research'),
    ('2', 'Draft Motion'),
    ('3', 'Draft Correspondence'),
    ('4', 'Hearing'),
    ('5', 'Administrative'),
    ('6', 'Status call'),
    ('7', 'Discovery'),
    ('8', 'Doc Review'),
    ('9', 'MISC')
)

TASKSTATUS = (
    ('O', 'Open'),
    ('C', 'Complete')
)

class Case(models.Model):
    name = models.CharField(max_length=20)
    client = models.CharField(max_length=20)
    attorney = models.CharField(max_length=20)
    date_opened = models.DateField(blank=True, null=True, default=datetime.date.today())
    date_closed = models.DateField(blank=True, null=True)
    description = models.TextField(max_length=500)
    case_status = models.CharField(
        max_length=1,
        choices=CASESTATUS,
        default=CASESTATUS[0][0]
    )
    case_stage = models.CharField(
        max_length=1,
        choices=CASESTAGE,
        default=CASESTAGE[0][0]
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    class Meta: 
        ordering = ['case_status']

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("case-detail", kwargs={"pk": self.pk})
    
   
    

class Task(models.Model):
    task_name = models.CharField(max_length=20)
    task_type = models.CharField(
        max_length=1,
        choices=TASKTYPE,
        default=TASKTYPE[0][0]
    )
    task_status = models.CharField(
        max_length=1,
        choices=TASKSTATUS,
        default=TASKSTATUS[0][0]
    )
    task_description = models.TextField(max_length=500)
    date_created = models.DateField(blank=True, null=True, default=datetime.date.today())
    date_closed = models.DateField(blank=True, null=True)
    estimated_time = models.IntegerField()
    actual_time = models.IntegerField(blank=True, null=True)
    task_id = models.ForeignKey
    
    case = models.ForeignKey(Case, on_delete=models.CASCADE)

    class Meta: 
        ordering = ['task_status']

    def __str__(self):
        return self.task_name
    
    def get_absolute_url(self):
        return reverse("task-detail", kwargs={"pk": self.pk})

main_app/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views import View
from .models import Case, Task
from django.contrib.auth.views import LoginView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django import forms
from django.urls import reverse
from django.utils import timezone


class Home(LoginView):
    template_name = "home.html"


def signup(request):
    error_message = ""
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("case-index")
        else:
            error_message = "Invalid sign up - try again"

    form = UserCreationForm()
    context = {"form": form, "error_message": error_message}
    return render(request, "signup.html", context)


def about(request):
    return render(request, "about.html")


@login_required
def case_index(request):
    cases = Case.objects.filter(user=request.user)
    return render(request, "cases/case_index.html", {"cases": cases})


@login_required
def case_detail(request, pk):
    case = Case.objects.get(pk=pk)
    tasks = Task.objects.filter(case=case)
    cases = Case.objects.filter(user=request.user)
    return render(
        request,
        "cases/case_detail.html",
        {"case": case, "cases": cases, "tasks": tasks},
    )


@login_required
def task_index(request):
    tasks = Task.objects.all()
    cases = Case.objects.filter(user=request.user)
    return render(request, "tasks/task_index.html", {"tasks": tasks, "cases": cases})


@login_required
def task_index2(request):
    tasks = Task.objects.all()
    cases = Case.objects.filter(user=request.user)
    return render(request, "tasks/task_index2.html", {"tasks": tasks, "cases": cases})


@login_required
def task_detail(request, pk):
    task = Task.objects.get(pk=pk)
    cases = Case.objects.filter(user=request.user)
    return render(request, "tasks/task_detail.html", {"task": task, "cases": cases})


def tasksDataAPI(request):
    data = Task.objects.all()
    dataList = []

    for i in data:
        dataList.append(
            {
                "task_name": i.task_name,
                "task_type": i.task_type,
                "task_status": i.task_status,
                "task_description": i.task_description,
                "estimated_time": i.estimated_time,
                "actual_time": i.actual_time,
                "id": i.task_id,
            }
        )

    return JsonResponse(dataList, safe=False)


class CaseCreate(LoginRequiredMixin, CreateView):
    model = Case

    fields = [
        "name",
        "client",
        "date_opened",
        "date_closed",
        "description",
        "case_status",
        "case_stage",
    ]
    success_url = "/cases/"

    def form_valid(self, form):
        form.instance.user = self.request.user
        response = super().form_valid(form)
        return redirect(reverse("case-detail", kwargs={"pk": self.object.pk}))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["cases"] = Case.objects.filter(user=self.request.user)
        context["form_title"] = "Create Case"
        return context


class CaseUpdate(LoginRequiredMixin, UpdateView):
    model = Case
    fields = ["client", "description", "case_status", "case_stage"]

    def get_success_url(self):
        return reverse("case-detail", kwargs={"pk": self.object.pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["cases"] = Case.objects.filter(user=self.request.user)
        return context


class CaseCloseView(View):
    def get(self, request, pk):
        case = Case.objects.get(pk=pk)
        case.case_status = "C"
        case.date_closed = timezone.now() 
        case.save()
        return redirect("case-detail", pk=pk)


class CaseDelete(LoginRequiredMixin, DeleteView):
    model = Case
    success_url = "/cases/"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["cases"] = Case.objects.filter(user=self.request.user)
        return context

class TaskCreate(LoginRequiredMixin, CreateView):
    model = Task
    fields = ['task_name', 'task_type', 'task_status', 'task_description', 'date_created', 'estimated_time', 'actual_time']  

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tasks"] = Task.objects.all()
        context["form_title"] = "Create Task"
        context["case"] = Case.objects.get(pk=self.kwargs["pk"])
        context["cases"] = Case.objects.filter(user=self.request.user)
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.case = Case.objects.get(pk=self.kwargs["pk"]) 
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('case-detail', kwargs={'pk': self.kwargs["pk"]})


class TaskUpdate(LoginRequiredMixin, UpdateView):
    model = Task
    fields = ['task_name', 'task_type', 'task_status', 'task_description', 'date_created', 'date_closed', 'estimated_time', 'actual_time'] 

    def form_valid(self, form):
        form.instance.user = self.request.user
        response = super().form_valid(form)
        task = self.object
        case = task.case
        return redirect(reverse("case-detail", kwargs={"pk": case.pk}))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tasks"] = Task.objects.all()
        context["cases"] = Case.objects.filter(user=self.request.user)
        return context


class TaskCloseView(LoginRequiredMixin, UpdateView):
    def get(self, request, pk):
        task = Task.objects.get(pk=pk)
        case = task.case
        task.task_status = "C"
        task.date_closed = timezone.now() 
        task.save()
        return redirect("case-detail", pk=case.pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["cases"] = Case.objects.filter(user=self.request.user)
        return context


class TaskDelete(LoginRequiredMixin, DeleteView):
    model = Task
    success_url = '/cases'

    def get(self, request, pk):
        task = Task.objects.get(pk=pk)
        case = task.case
        task.delete()
        return redirect("case-detail", pk=case.pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["cases"] = Case.objects.filter(user=self.request.user)
        return context

main_app/templates/cases/case_detail.html
{% extends "base.html" %}

{% load static %}

{% block title %}Case Details{% endblock %}

{% block head %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" />
  <link href='{% static 'css/bootstrap.min.css' %}' rel='stylesheet'> 
  <link rel="stylesheet" href="{% static 'css/base.css' %}" />
{% endblock %}

{% block content %}
<div class="case-details-wrapper content">
  <h2>{{ case.name }}</h2>
  <div class="case-details mb-4">
    <p><strong>Client:</strong> {{ case.client }}</p>
    <p><strong>Description:</strong> {{ case.description }}</p>
    <p><strong>Date Opened:</strong> {{ case.date_opened }}</p>
    <p><strong>Date Closed:</strong> {{ case.date_closed }}</p>
    <p><strong>Case Stage:</strong> {{ case.get_case_stage_display }}</p>
    <p><strong>Case Status:</strong> {{ case.get_case_status_display }}</p>
  </div>
  <div class="action-buttons-container mb-4">
    <a href="{% url 'case-update' case.pk %}" class="action-button btn btn-info">UPDATE</a>
    <a href="{% url 'case-close' case.pk %}" class="action-button btn btn-success">CLOSE</a>
  </div>


  <div class="container-fluid px-0">
    <div class="row">
      <div class="col-12">
        <a href="{% url 'task-create' case.pk %}">
        <button type="submit" class="btn btn-primary mb-3" id="task-create">
  <i class="fa-regular fa-square-plus fa-lg me-1"></i>Add Task
</button>
</a>
        {% if tasks %}
        <div class="card border-info mb-4">
          <div class="card-header">{{ case.name }} Case Tasks</div>
          <div class="card-body p-0">
            <div class='table-responsive'>
              <table class="table table-hover mb-0" id="tasksTable">
                <thead>
                  <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Type</th>
                    <th scope="col">Status</th>
                    <th scope="col">Est. Time</th>
                    <th scope="col">Actual Time</th>
                    <th class="task-buttons" scope="col">Actions</th>
                  </tr>
                </thead>
                <tbody id='myTasks'>
                  {% for task in tasks %}
                  <tr>
                    <td>{{ task.task_name }}</td>
                    <td>{{ task.get_task_type_display }}</td>
                    <td>{{ task.get_task_status_display }}</td>
                    <td>{{ task.estimated_time }}</td>
                    <td>{{ task.actual_time }}</td>
                    <td>
                      <a class='btn btn-primary btn-sm me-1' href='{% url 'task-detail' task.pk %}'><i class="fa-solid fa-arrow-up-right-from-square"></i></a>
                      <a class='btn btn-info btn-sm me-1' href='{% url 'task-update' task.pk %}'><i class="fa-regular fa-pen-to-square"></i></a>
                      <a class='btn btn-success btn-sm me-1' href='{% url 'task-close' task.pk %}'><i class="fa-regular fa-square-check"></i></a>
                      <a class='btn btn-danger btn-sm me-1' href='{% url 'task-delete' task.pk %}'><i class="fa-regular fa-trash-can"></i></a>
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
        {% else %}
        <h4 class='alert alert-primary mb-4'>{{ case.name }} has no tasks!</h4>
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block extra_content %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://code.jquery.com/jquery-3.4.1.js"></script>
<script>
  $(document).ready(function() {
    // Function to add task row
    function addTaskRow(task) {
      const row = `<tr scope="row" class="task-row-${task.id}">
                      <td>${task.task_name}</td>
                      <td>${task.task_type}</td>
                      <td>${task.task_status}</td>
               
                      <td>${task.estimated_time}</td>
                      <td>${task.actual_time}</td>
                      <td>
                        <a class='btn btn-primary btn-sm me-1' href='/tasks/${task.id}/detail'><i class="fa-solid fa-arrow-up-right-from-square"></i></a>
                        <a class='btn btn-warning btn-sm me-1' href='/tasks/${task.id}/update'><i class="fa-regular fa-pen-to-square"></i></a>
                        <a class='btn btn-success btn-sm me-1' href='/tasks/${task.id}/close'><i class="fa-regular fa-square-check"></i></a>
                        <a class='btn btn-danger btn-sm me-1' href='/tasks/${task.id}/delete'><i class="fa-regular fa-trash-can"></i></a>
                      </td>
                  </tr>`;
      $('#tasksTable').append(row);
    }

    // Fetch tasks from API and populate table
    const dataURL = '/tasksapi/';
    $.ajax({
      method: 'GET',
      url: dataURL,
      success: function(response) {
        response.forEach(task => {
          addTaskRow(task);
        });
      }
    });

    // Handle create task button click
    $('#task-create').on('click', function() {
      // Define new task object
      let taskId = 1;
      let newTask = {
        task_name: 'New Task',
        id: `task-${taskId}`,
        task_type: 'Type',
        task_status: 'Status',
        estimated_time: 'Estimated Time',
        actual_time: 'Actual Time'
      };

      // Append new task to table and increment taskId
      addTaskRow(newTask);
      taskId++;
    });
  });
</script>
{% endblock %}

main_app/templates/cases/case_index.html
{% extends "base.html" %}
{% load static %}

{% block title %}Case Index - Caselawg{% endblock %}

{% block content %}
<h1>Cases</h1>
<p>Select a case from the sidebar to view its details.</p>
{% endblock %}